version: '3.8'

services:
  portal-jakinet:
    image: portal-jakinet:latest
    container_name: portal-jakinet-app
    restart: always
    ports:
      - "3001:3000" # Map host port 3001 (sesuai .env) ke container port 3000
    env_file:
      - .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "jpo.jelantik.com:172.67.148.202"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
